FROM java:openjdk-8

# File Author / Maintainer
MAINTAINER Tavisca Solutions

# Install update
RUN apt-get -y update && \
    apt-get -y update && \
    apt-get -y install unzip && \
    apt-get -y install software-properties-common

